# Generated by Django 5.1.7 on 2026-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_dropoff_lat_delivery_dropoff_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='tracking_key',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
